Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,6 +13,7 @@ env:
    global:
    - TAG=nightly
    - RECREATE_TAGS=false
+   - NO_COMMIT=''
 
 install:
   - export SHORT_SHA=$(git rev-parse --short HEAD)
@@ -102,9 +103,31 @@ jobs:
   #         else
   #           echo "[INFO] No existing tags detected for $VERSION"
   #         fi
-  
+
    - stage: Build images for release version
-     name: build image on amd64
+     name: Check existing tags
+     if: branch != master AND env(TAG) != "nightly"
+     arch: amd64
+     script: 
+     - |
+       set +e
+       echo "GITHUB TOKEN:$GITHUB_TOKEN" 
+       RECREATE_TAGS=$RECREATE_TAGS
+       VERSION=$TAG
+       EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
+       if [[ -n ${EXISTING_TAG} ]]; then
+          if [[ ${RECREATE_TAGS} == "true" ]]; then
+            echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
+            git push origin :$VERSION
+          else
+            echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+            exit 1
+          fi
+       else
+          echo "[INFO] No existing tags detected for $VERSION"
+       fi
+
+   - name: build image on amd64
      if: branch != master AND env(TAG) != "nightly"
      arch: amd64
      script:
@@ -132,7 +155,9 @@ jobs:
      if: env(TAG) != "nightly"
      script: bash .travis/publish_multiarch.sh $TAG
      after_success:
-       - git config --global user.name "Prabhav Thali"
-       - git config --global user.email "Prabhav.Thali1@ibm.com"
+       - git config --global user.name "Mykhailo Kuznietsov"
+       - git config --global user.email "mkuznets@redhat.com"
+       - echo $GITHUB_TOKEN
        - export GITHUB_TOKEN=$GITHUB_TOKEN
-       - bash make-release.sh --version $TAG --tag-release
+       - echo $GITHUB_TOKEN
+       - bash make-release.sh --version $TAG --tag-release $NO_COMMIT
