Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -83,28 +83,28 @@ jobs:
      if: branch = travis-s390x AND env(TAG) = "nightly"
      script: bash .travis/publish_multiarch.sh $TAG
 
+  #  - name: Check existing tags
+  #    if: branch != master AND env(TAG) != "nightly"
+  #    arch: amd64
+  #    script: |
+  #         set +e
+  #         RECREATE_TAGS=$RECREATE_TAGS
+  #         VERSION=$TAG
+  #         EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
+  #         if [[ -n ${EXISTING_TAG} ]]; then
+  #           if [[ ${RECREATE_TAGS} == "true" ]]; then
+  #             echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
+  #             git push origin :$VERSION
+  #           else
+  #             echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+  #             exit 1
+  #           fi
+  #         else
+  #           echo "[INFO] No existing tags detected for $VERSION"
+  #         fi
+  
    - stage: Build images for release version
-   - name: Check existing tags
-     if: branch != master AND env(TAG) != "nightly"
-     arch: amd64
-     script: |
-          set +e
-          RECREATE_TAGS=$RECREATE_TAGS
-          VERSION=$TAG
-          EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
-          if [[ -n ${EXISTING_TAG} ]]; then
-            if [[ ${RECREATE_TAGS} == "true" ]]; then
-              echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
-              git push origin :$VERSION
-            else
-              echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
-              exit 1
-            fi
-          else
-            echo "[INFO] No existing tags detected for $VERSION"
-          fi
-
-   - name: build image on amd64
+     name: build image on amd64
      if: branch != master AND env(TAG) != "nightly"
      arch: amd64
      script:
@@ -129,7 +129,7 @@ jobs:
        - bash .travis/build_nightly.sh $TAG
 
    - stage: Publish multiarch image with release tag
-     if: branch != master AND env(TAG) != "nightly"
+     if: env(TAG) != "nightly"
      script: bash .travis/publish_multiarch.sh $TAG
      after_success:
        - git config --global user.name "Prabhav Thali"
